/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientpcstransaksi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pcs.entitas.Item;
import pcs.entitas.Produk;
import pcs.entitas.Transaksi;
import pcs.remoteserver.RemoteServerLogin;
import pcs.remoteserver.RemoteServerTransaksi;

/**
 *
 * @author Wiwi
 */
public class FrmTransaksiXXXX extends javax.swing.JFrame {

    private String namaOp;
    private RemoteServerTransaksi rst;
    private RemoteServerLogin rsl;
    private int iFrm;
    private DefaultTableModel dtmItem;
    private Produk DtProduk = new Produk();
    private List<Produk> listPro = new ArrayList<Produk>();
    private final FrmCariProdukXXXX frmCariProduk = new FrmCariProdukXXXX();
    private boolean statusProses;
    DecimalFormat dfo = new DecimalFormat("#,##0");

    public void setRst(RemoteServerTransaksi rst) {
        this.rst = rst;
    }

    public void setRsl(RemoteServerLogin rsl) {
        this.rsl = rsl;
    }

    public void setiFrm(int iFrm, String nama) {
        this.iFrm = iFrm;
        setNamaOp(nama);
        setTitle("Operator:" + nama + "_" + iFrm);
    }

    public void setNamaOp(String namaOp) {
        this.namaOp = namaOp;
    }

    public void aturTblItem() {
        dtmItem = (DefaultTableModel) tblItem.getModel();
        dtmItem.setRowCount(0);
        for (int i = 0; i < listPro.size(); i++) {
            dtmItem.addRow(
                    new Object[]{listPro.get(i).getKode(), listPro.get(i).getNama(),
                        listPro.get(i).getHarga(), listPro.get(i).getDiskon()});
        }
    }

    public void hitungTotal() {
        double total = 0;
        if (dtmItem.getColumnCount() > 0) {
            for (int i = 0; i < dtmItem.getRowCount(); i++) {
                total += Double.valueOf(dtmItem.getValueAt(i, 5).toString());
            }
        }
        lblTotal.setText(String.valueOf(dfo.format(total)));
    }

    /** Creates new form FrmTransaksi */
    public FrmTransaksiXXXX() {
        initComponents();
        String tgl = new SimpleDateFormat("yyyy/MM/dd hh:mm:ss").format(
                new Date()).toString();
        lblTglNota.setText(tgl);
        aturTblItem();

        frmCariProduk.getBtnPilih().addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (frmCariProduk.getTblProduk().getRowCount() > 0) {
                    int barisKe = frmCariProduk.getTblProduk().getSelectedRow();
                    DtProduk.setKode(
                            frmCariProduk.getTblProduk().getModel().getValueAt(
                            barisKe, 0).toString());
                    DtProduk.setNama(
                            frmCariProduk.getTblProduk().getModel().getValueAt(
                            barisKe, 1).toString());
                    DtProduk.setHarga(Double.valueOf(
                            frmCariProduk.getTblProduk().getModel().getValueAt(
                            barisKe, 2).toString()));
                    DtProduk.setDiskon(Double.valueOf(
                            frmCariProduk.getTblProduk().getModel().getValueAt(
                            barisKe, 3).toString()));
                    txtKdProduk.setText(DtProduk.getKode());
                    txtNama.setText(DtProduk.getNama());
                    txtBanyak.requestFocus();
                    frmCariProduk.dispose();
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtKdProduk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBanyak = new javax.swing.JTextField();
        btnBatalkanItem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUangDibayarkan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblUangKembali = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblTglNota = new javax.swing.JLabel();
        btnCariProduk = new javax.swing.JButton();
        txtKdMember = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi"));

        jLabel5.setText("Kode");

        txtKdProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdProdukActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama Produk");

        jLabel6.setText("Byk");

        txtBanyak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBanyak.setText("1");
        txtBanyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanyakActionPerformed(evt);
            }
        });
        txtBanyak.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBanyakFocusGained(evt);
            }
        });
        txtBanyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBanyakKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBanyakKeyTyped(evt);
            }
        });

        btnBatalkanItem.setText("Batalkan Item");
        btnBatalkanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalkanItemActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Enter");

        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Enter");

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Produk", "Byk", "Harga", "Disc", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItem);
        tblItem.getColumnModel().getColumn(0).setResizable(false);
        tblItem.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblItem.getColumnModel().getColumn(1).setResizable(false);
        tblItem.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblItem.getColumnModel().getColumn(2).setResizable(false);
        tblItem.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblItem.getColumnModel().getColumn(3).setResizable(false);
        tblItem.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblItem.getColumnModel().getColumn(4).setResizable(false);
        tblItem.getColumnModel().getColumn(4).setPreferredWidth(30);
        tblItem.getColumnModel().getColumn(5).setResizable(false);
        tblItem.getColumnModel().getColumn(5).setPreferredWidth(70);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtKdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBatalkanItem))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnBatalkanItem))
        );

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 48));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jLabel8.setText("Uang Dibayarkan:");

        txtUangDibayarkan.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtUangDibayarkan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUangDibayarkan.setText("0");
        txtUangDibayarkan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUangDibayarkanFocusGained(evt);
            }
        });
        txtUangDibayarkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangDibayarkanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUangDibayarkanKeyTyped(evt);
            }
        });

        jLabel9.setText("Uang Kembali      :");

        lblUangKembali.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblUangKembali.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUangKembali.setText("0");
        lblUangKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("Tanggal :");

        lblTglNota.setBackground(new java.awt.Color(204, 204, 204));
        lblTglNota.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTglNota.setText("lblTglNota");

        btnCariProduk.setText("Cari Produk");
        btnCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdukActionPerformed(evt);
            }
        });

        txtKdMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdMemberActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan kode member :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTglNota, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProses)
                        .addGap(2, 2, 2)
                        .addComponent(btnTutup))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtKdMember, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUangKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUangDibayarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTglNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnCariProduk))
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUangDibayarkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTutup)
                            .addComponent(btnProses)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKdMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        try {
            // TODO add your handling code here:
            frmCariProduk.aturTabelProduk(rst.selectProduk());
            frmCariProduk.setLocationRelativeTo(null);
            frmCariProduk.setVisible(true);

        } catch (RemoteException ex) {
            Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnBatalkanItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalkanItemActionPerformed
        // TODO add your handling code here:
        if (tblItem.getSelectedRow() >= 0) {
            dtmItem.removeRow(tblItem.getSelectedRow());
            hitungTotal();
        }
    }//GEN-LAST:event_btnBatalkanItemActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        try {
            rsl.hapusClient(iFrm, namaOp);
        } catch (RemoteException ex) {
            Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(
                    Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        double dibayar = 0;
        try {
            dibayar = new DecimalFormat("###0").parse(
                    txtUangDibayarkan.getText()).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (dibayar == 0) {
            JOptionPane.showMessageDialog(this,
                    "Masukkan Uang yang dibayarkan!", "Pemberitahuan",
                    JOptionPane.WARNING_MESSAGE);
            txtUangDibayarkan.requestFocus();
        } else if (txtKdMember.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Masukkan Kode Member!", "Pemberitahuan",
                    JOptionPane.WARNING_MESSAGE);
            txtKdMember.requestFocus();
        } else {
            Transaksi dataTransaksi = new Transaksi();
            dataTransaksi.setKodeMember(txtKdMember.getText());

            try {
                dataTransaksi.setTglNota(new SimpleDateFormat(
                        "yyyy/MM/dd hh:mm:ss").parse(lblTglNota.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(
                        Level.SEVERE, null, ex);
            }
            List<Item> listItem = new ArrayList<Item>();
            Item item = new Item();

            for (int i = 0; i < tblItem.getRowCount(); i++) {
                item.setKdProduk(dtmItem.getValueAt(i, 0).toString());
                item.setBanyak(Integer.valueOf(
                        dtmItem.getValueAt(i, 2).toString()));
                listItem.add(item);
                aturTblItem();
            }
            
            try {
                statusProses = rst.insertTransaksi(dataTransaksi, listItem);
            } catch (RemoteException ex) {
                System.out.println(ex.getMessage());
                statusProses = false;
                Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(
                        Level.SEVERE, null, ex);
            }
            if (statusProses) {
                JOptionPane.showMessageDialog(rootPane, "proses berhasil",
                        "info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "proses gagal",
                        "error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            rsl.hapusClient(iFrm, namaOp);
        } catch (RemoteException ex) {
            Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(
                    Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtKdProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdProdukActionPerformed
        // TODO add your handling code here:
        if (!txtKdProduk.getText().isEmpty()) {
            for (int i = 0; i < listPro.size(); i++) {
                if (listPro.get(i).getKode().equals(txtKdProduk.getText())) {
                    DtProduk.setKode(listPro.get(i).getKode());
                    DtProduk.setNama(listPro.get(i).getNama());
                    DtProduk.setHarga(listPro.get(i).getHarga());
                    DtProduk.setDiskon(listPro.get(i).getDiskon());
                    break;
                }
            }
            txtNama.setText(DtProduk.getNama());
            txtBanyak.requestFocus();
        }
    }//GEN-LAST:event_txtKdProdukActionPerformed

    private void txtBanyakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBanyakKeyTyped
        // TODO add your handling code here:      
        try {
            Integer.valueOf(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException e) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtBanyakKeyTyped

    private void txtBanyakFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanyakFocusGained
        // TODO add your handling code here:
        txtBanyak.selectAll();
    }//GEN-LAST:event_txtBanyakFocusGained

    private void txtBanyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanyakActionPerformed
        // TODO add your handling code here:
        String kode = DtProduk.getKode();
        String nama = DtProduk.getNama();
        double harga = DtProduk.getHarga();
        double dis = DtProduk.getDiskon();
        int byk = Integer.valueOf(txtBanyak.getText());
        double subtotal = byk * harga - (harga * dis);
        dtmItem.addRow(new Object[]{kode, nama, byk, harga, dis, subtotal});
        hitungTotal();
        txtKdProduk.setText("");
        txtNama.setText("");
        txtBanyak.setText("1");
        txtKdProduk.requestFocus();
    }//GEN-LAST:event_txtBanyakActionPerformed

    private void txtBanyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBanyakKeyReleased
        // TODO add your handling code here:
        if (txtBanyak.getText().isEmpty()) {
            txtBanyak.setText("1");
        }

    }//GEN-LAST:event_txtBanyakKeyReleased

    private void txtUangDibayarkanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangDibayarkanKeyReleased
        // TODO add your handling code here:
        if (txtUangDibayarkan.getText().isEmpty()) {
            txtUangDibayarkan.setText("0");
        }
        double total = 0;
        double dibayar = 0;
        try {
            total = new DecimalFormat("#,##0.00").parse(
                    lblTotal.getText()).doubleValue();
            dibayar = new DecimalFormat("#,##0").parse(
                    txtUangDibayarkan.getText()).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(FrmTransaksiXXXX.class.getName()).log(
                    Level.SEVERE, null, ex);
        }

        txtUangDibayarkan.setText(dfo.format(dibayar));
        double uangKembali = Double.valueOf(dibayar - total);
        lblUangKembali.setText(dfo.format(uangKembali));
    }//GEN-LAST:event_txtUangDibayarkanKeyReleased

    private void txtUangDibayarkanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUangDibayarkanFocusGained
        // TODO add your handling code here:
        txtUangDibayarkan.selectAll();
    }//GEN-LAST:event_txtUangDibayarkanFocusGained

    private void txtUangDibayarkanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangDibayarkanKeyTyped
        // TODO add your handling code here:
        try {
            Integer.valueOf(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException e) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtUangDibayarkanKeyTyped

    private void txtKdMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdMemberActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new FrmTransaksiXXXX().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalkanItem;
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTglNota;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUangKembali;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtBanyak;
    private javax.swing.JTextField txtKdMember;
    private javax.swing.JTextField txtKdProduk;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUangDibayarkan;
    // End of variables declaration//GEN-END:variables
}
